import Card from "../ui/Card";
import Badge from "../ui/Badge";
import Progress from "../ui/Progress";

interface Props {
  committee: any;
}

export default function RecommendationCard({
  committee,
}: Props) {

  const recommendation = committee.recommendation;

  const color =
    recommendation === "Strong Buy"
      ? "green"
      : recommendation === "Buy"
      ? "green"
      : recommendation === "Hold"
      ? "yellow"
      : recommendation === "Watch"
      ? "orange"
      : "red";

  return (
    <Card>

      <div className="flex justify-between items-center">

        <div>

          <h2 className="text-2xl font-bold">
            Investment Recommendation
          </h2>

          <p className="text-gray-400 mt-1">
            Generated by InvestIQ AI Committee
          </p>

        </div>

        <Badge
          text={recommendation}
          color={color as any}
        />

      </div>

      <div className="mt-8">

        <Progress
          value={committee.confidence}
        />

        <div className="flex justify-between mt-2 text-sm">

          <span>Confidence</span>

          <span>
            {committee.confidence}%
          </span>

        </div>

      </div>

    </Card>
  );
}
