import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generatePDF(analysis: any) {
  const doc = new jsPDF();

  const financial = analysis.financial;
  const market = analysis.market;
  const committee = analysis.committee;

  // ===== Title =====
  doc.setFontSize(22);
  doc.text("InvestIQ AI", 20, 20);

  doc.setFontSize(15);
  doc.text("Investment Analysis Report", 20, 30);

  // ===== Company =====
  doc.setFontSize(16);
  doc.text("Company Information", 20, 45);

  autoTable(doc, {
    startY: 50,
    head: [["Field", "Value"]],
    body: [
      ["Company", financial.profile.name],
      ["Ticker", financial.profile.ticker],
      ["Industry", financial.profile.finnhubIndustry],
      ["Country", financial.profile.country],
      ["Exchange", financial.profile.exchange],
      ["IPO", financial.profile.ipo],
    ],
  });

  // ===== Recommendation =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Recommendation", "Confidence"]],
    body: [
      [
        committee.recommendation,
        `${committee.confidence}%`,
      ],
    ],
  });

  // ===== Scores =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Metric", "Score"]],
    body: [
      ["Overall", financial.scores.overall],
      ["Valuation", financial.scores.valuation],
      ["Growth", financial.scores.growth],
      ["Risk", financial.scores.risk],
    ],
  });

  // ===== Market =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Market", "Value"]],
    body: [
      ["Current Price", `$${market.currentPrice}`],
      ["Previous Close", `$${market.previousClose}`],
      ["Day High", `$${market.dayHigh}`],
      ["Day Low", `$${market.dayLow}`],
      ["Trend", market.trend],
    ],
  });

  // ===== Reasons =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Investment Reasons"]],
    body: committee.reasons.map((item: string) => [item]),
  });

  // ===== Strengths =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Strengths"]],
    body: committee.strengths.map((item: string) => [item]),
  });

  // ===== Weaknesses =====
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Weaknesses"]],
    body:
      committee.weaknesses.length > 0
        ? committee.weaknesses.map((item: string) => [item])
        : [["No major weaknesses detected"]],
  });

  // ===== Footer =====
  doc.setFontSize(10);

  doc.text(
    "Generated by InvestIQ AI",
    20,
    285
  );

  doc.text(
    "Developed by Aditya Kumar Singh",
    20,
    291
  );

  doc.save(
    `InvestIQ_${financial.profile.ticker}.pdf`
  );
}